### ISSUE TITLE
What

### ISSUE THREAD

**Issue by MarosLodnipeguh** [N3agu/Drakensang-Injector#1]
Hello, what exactly does this code inject to the dll? and what dll are we talking about?

**Comment by N3agu** [comment]
Hello, this was a cheat injector made for a game I played when I was a kid, called [drakensang](https://www.drakensang.com/en). I didn't made public the cheat as well because I lost the project. If you wrote your own cheat, all you need to do is rename the dll to "DSO_Internal_Cheat.dll" / make the program use args / change the name of the dll in the code and run the injector.
